CREATE TABLE IF NOT EXISTS comida (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	tipo VARCHAR(30) NOT NULL,
	picante BOOLEAN NOT NULL,
	perfil VARCHAR(30) NOT NULL,
	grasa VARCHAR(30) NOT NULL
);
